### PR TITLE
Adding some comment to the README file

### PR DESCRIPTION
**Pull request by IvanGutierrezMartinez**
Making it easier for people to understand what this project is about.

### CODE REVIEW

**Comment by IvanGutierrezMartinez** [comment]
Probando los comentarios :)

**Comment by IvanGutierrezMartinez** [comment]
:yum:

**Comment by IvanGutierrezMartinez** [comment]
:smiley:

**Comment by IvanGutierrezMartinez** [comment]
https://www.google.cl/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0CAcQjRxqFQoTCJSJoP22gcgCFcWTkAodTGkIZQ&url=%2Furl%3Fsa%3Di%26rct%3Dj%26q%3D%26esrc%3Ds%26source%3Dimages%26cd%3D%26cad%3Drja%26uact%3D8%26ved%3D0CAcQjRxqFQoTCJSJoP22gcgCFcWTkAodTGkIZQ%26url%3Dhttps%253A%252F%252Founomachi.wordpress.com%252F2013%252F02%252F12%252Fonepunch-man%252F%26psig%3DAFQjCNFIxI988F8xGkwCpSbu3rSXi3ISZA%26ust%3D1442694769451312&psig=AFQjCNFIxI988F8xGkwCpSbu3rSXi3ISZA&ust=1442694769451312

**Comment by IvanGutierrezMartinez** [comment]
revisar por favor

**Comment by brntbeer** [comment]
This PR needs to be closed so i can delete the branch it's coming from. Thanks for the pull request, keep your eye out for a new version of the book soon! ❤️

**Pull request closed without merging**
