### PR TITLE
Update readme 2

### PR DESCRIPTION
**Pull request by jyshen**

### CODE REVIEW

**Comment by kevleininger** [comment]
Test of comments.  What do you think @kevleininger

**Comment by elguapo4twenty** [comment]
:+1:

**Comment by zangchung** [comment]
:)

**Comment by zangchung** [comment]
:+1: :ship:

**Comment by brntbeer** [comment]
getting a new version of the book out with @PeterBell (I know, it's about time). Closing and deleting this branch! ❤️

**Pull request closed without merging**
